# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS on Alpine for a lightweight image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source files
COPY tsconfig.json .
COPY src ./src

# Build the TypeScript code
RUN npm run build

# ---- Runtime image ----
FROM node:18-alpine AS runtime
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Ensure built scripts are executable
RUN chmod +x dist/*.js

# Default command
CMD ["node", "dist/index.js"]
